# docker build -t clean-kongs .
# interactive shell to view image: docker run -it clean-kongs sh
# exit
# to clean build cache: docker builder prune
# container iD: e4cc793f4680
# to stop: docker stop e4cc793f4680
# to remove: docker rm e4cc793f4680
# to view images and their containers IDs: docker ps -a
# docker build -t us-central1-docker.pkg.dev/jadu-e23c4/clean-kong/clean-kong-app:v1 .
# docker push us-central1-docker.pkg.dev/jadu-e23c4/clean-kong/clean-kong-app:v1
# requires: gcloud auth configure-docker us-central1-docker.pkg.dev

FROM nytimes/blender:latest

ADD failed ./failed
ADD cleaned ./cleaned

COPY clean_skipped.sh ./
COPY glb.py ./

RUN chmod +x clean_skipped.sh

RUN apt-get update
RUN apt-get install curl -y

ENV CLOUD_KEY=ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltSm9aVE5wTkhJd1oxUXRhMVZEWTJOelpWQjZNVFF0VUY5MmIzZEdUelZOTUZkSVRqUjBSRkl0VVZraWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExXNXZaR1V0YkdWaGMyVWlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObFkzSmxkQzV1WVcxbElqb2laR1ZtWVhWc2RDMTBiMnRsYmkxb2NHZzNOQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG01aGJXVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpYSjJhV05sTFdGalkyOTFiblF1ZFdsa0lqb2lOV1F6TUdRek1XTXRaVEprTlMwMFpEVm1MV0ptTVRNdE9UaGpNalJsWXpWbE56Z3pJaXdpYzNWaUlqb2ljM2x6ZEdWdE9uTmxjblpwWTJWaFkyTnZkVzUwT210MVltVXRibTlrWlMxc1pXRnpaVHBrWldaaGRXeDBJbjAuaXljajRoYkFfYTFzX3RmbEdteTRwZHRUMXFWZWszeHlSaFBoQTc3bzN1aTQ2dkVJTENuaTlGOUc4b2U2bHRWU20xUHlpVnJKOThyMUlCNWZaTFNUY3A5dEw2S3ZMNW5nSFpfN3EwYnlqb0xwR3R5U2llVVpRSXFOd3RGaHkxYTZaVEk5VzZ1dS1PbGluXy1KREFSTnZPM1YzZjRFbnhuTkhFcS1PUFFDRGVMZE00YmtHQmVZb1k5V2h3bENUX0Y0aDV2RUo2bGRzREZ5cXZ0VzNLNmo5bENSSXl6ZXd5cjN3OW5kRHVHT1ROc1RpYWI5YTlhZWpkWDZ1TkZaa2hhSGtXUF9KXzJvTzFnRHVvR1dIcFFYTDlWZ3Z5X0hRUmF4SEVVM2ZfX2l2X3FsNzA2V21Nc2RPc0RCWF9HVmtKWnFSVFZlSWZ0UmVaeTlHNUEwamNEOWpR

CMD ["./clean_skipped.sh"]